serviceAccountId: stripe-dev
servieAccountType: STRIPE
listener: charge.succeeded
triggers:
  -
    eventId: add-action-rule
    payload:
      action:
        id: String
        name: String
        config: any
        serviceAction: String
        serviceAccountId: String
      ruleId: String
      eventId: String
      triggers: Array
      namespace: String
  -
    eventId: add-question
    payload:
      email: String
      subject: String
      question: String
      namespace: String
source_model:
  id: String
  object: String
  amount: Number
  amount_refunded: Number
  application: String
  application_fee: String
  application_fee_amount: Number
  balance_transaction: String
  captured: Boolean
  created: Number
  currency: String
  customer: String
  description: String
  destination: String
  dispute: String
  failure_code: String
  failure_message: String
  fraud_details:
    stripe_report: String
    user_report: String
  invoice: String
  livemode: Boolean
  metadata: Object
  on_behalf_of: String
  order: String
  outcome: Object
  paid: Boolean
  payment_intent: String
  receipt_email: String
  receipt_number: String
  receipt_url: String
  refunded: Boolean
  refunds:
    object: String
    data: Array
    has_more: Boolean
    total_count: Number
    url: String
  review: String
  shipping: String
  source:
    id: String
    object: String
    address_city: String
    address_country: String
    address_line1: String
    address_line1_check: String
    address_line2: String
    address_state: String
    address_zip: String
    address_zip_check: String
    brand: String
    country: String
    customer: String
    cvc_check: String
    dynamic_last4: String
    exp_month: Number
    exp_year: Number
    fingerprint: String
    funding: String
    last4: String
    metadata: Object
    name: String
    tokenization_method: String
  source_transfer: String
  statement_descriptor: String
  status: String
  transfer_data:
    destination: String
  transfer_group: String
